name: SSE CI/CD

on:
  push:
  
jobs:
  style_check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run black
      run: black . --check 
    
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage matplotlib numpy
      - name: Create coverage Report
        run: coverage run -m pytest
      - name: Upload Coverage Report Folder
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: .coverage
          retention-days: 1
          
  coverage_report:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage
      - uses: actions/download-artifact@v3
        with:
          name: coverage_report
      - run: ls -R
      - name: Create Coverage Report
        run: |
          coverage report
          coverage xml
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          path: coverage.xml
          retention-days: 14
      
